### ISSUE TITLE
Adjust the view for un-authenticated user

### ISSUE THREAD

**Issue by remote-how-iwo** [AI-AI-Boyzz/web-ui#1]
**Problem** Now, when a user enters the chat, they see that it's a chat, so they want to write automatically but can only talk once they are authenticated. We need to adjust it somehow.

**Solution:**

1. Expand the text to the button.

>  If you want to start talking to me, **sign in with Gmail**.

2. Block the user from adding text to the chat input field?

![Image](https://user-images.githubusercontent.com/107128351/248227430-d46e428c-07a2-4971-849d-d770df95eaee.png)

**Comment by JelNiSlaw** [comment]
This is fixed by replacing the input field with the sign-in button
