### ISSUE TITLE
Fix how www chatbot display link to the playbook - how it's broken/not visible well

### ISSUE THREAD

**Issue by remote-how-iwo** [AI-AI-Boyzz/web-ui#16]
![Image](https://user-images.githubusercontent.com/107128351/248558887-cee57de6-8587-4ba3-b0b7-113589f9f4ba.png)

**Comment by JelNiSlaw** [comment]
![Image](https://github.com/AI-AI-Boyzz/web-ui/assets/25802745/0f1c19e1-b2c3-42e2-ac52-b6eac05aa29b)
