### ISSUE TITLE
Error when talking to chatbot

### ISSUE THREAD

**Issue by remote-how-iwo** [AI-AI-Boyzz/web-ui#4]
![Image](https://user-images.githubusercontent.com/107128351/248275084-09c79b6f-e700-4920-b0be-3999828f3ede.png)

**Comment by remote-how-iwo** [comment]
but after writing sth again, it worked although it provided wrong info...

![Image](https://github.com/AI-AI-Boyzz/web-ui/assets/107128351/7f49600c-f38c-4404-b258-1ff2329b9f6d)

**Comment by JelNiSlaw** [comment]
This is a general connection issue. I don't have enough information to debug it further
